
#ifndef _ACCESS_MSG_H_
#define _ACCESS_MSG_H_

#include <string>

struct access_msg_head {
	unsigned int sequece = 0;
	unsigned int content_len = 0;
};

#define ACCESS_CMD_VERSION                       "camera._version"
#define ACCESS_CMD_SET_OPTION                    "camera._setOptions"
#define ACCESS_CMD_GET_OPTION                    "camera._getOptions"
#define ACCESS_CMD_START_PREVIEW                 "camera._startPreview"
#define ACCESS_CMD_RESTART_PREVIEW               "camera._restartPreview"
#define ACCESS_CMD_STOP_PREVIEW                  "camera._stopPreview"
#define ACCESS_CMD_START_RECORD                  "camera._startRecording"
#define ACCESS_CMD_STOP_RECORD                   "camera._stopRecording"
#define ACCESS_CMD_START_LIVE                    "camera._startLive"
#define ACCESS_CMD_STOP_LIVE                     "camera._stopLive"
#define ACCESS_CMD_TAKE_PICTURE                  "camera._takePicture"
#define ACCESS_CMD_RESET				         "camera._reset"
#define ACCESS_CMD_QUREY_STATE                   "camera._queryState"
#define ACCESS_CMD_SET_OFFSET                    "camera._setOffset"
#define ACCESS_CMD_GET_OFFSET                    "camera._getOffset"
#define ACCESS_CMD_GET_IMAGE_PARAM               "camera._getImageParam"
#define ACCESS_CMD_CHANGE_STORAGE_PATH           "camera._changeStoragePath"
#define ACCESS_CMD_QUERY_STORAGE              	 "camera._queryStorage"
#define ACCESS_CMD_GET_VERSION                   "camera._getVersion"
#define ACCESS_CMD_GET_FW_VERSION                "camera._getFWVersion"
#define ACCESS_CMD_CALIBRATION                   "camera._calibration"
#define ACCESS_CMD_UPGRADE_FW                    "camera._upgradeFw"
#define ACCESS_CMD_CALIBRATION_AWB               "camera._calibrationAwb"
#define ACCESS_CMD_CALIBRATION_BPC               "camera._calibrationBpc"
#define ACCESS_CMD_CALIBRATION_BLC               "camera._calibrationBlc"
#define ACCESS_CMD_START_QRCODE_SCAN             "camera._startQRCodeScan"
#define ACCESS_CMD_STOP_QRCODE_SCAN              "camera._stopQRCodeScan"
#define ACCESS_CMD_FORMAT_CAMERA_MOUDLE          "camera._formatCameraMoudle"
#define ACCESS_CMD_STORAGE_SPEED_TEST            "camera._storageSpeedTest"
#define ACCESS_CMD_GYRO_CALIBRATION              "camera._gyroCalibration"
#define ACCESS_CMD_MAGMETER_CALIBRATION          "camera._magmeterCalibration"
#define ACCESS_CMD_POWEROFF                      "camera._powerOff" 
#define ACCESS_CMD_LOW_BAT_ACT                   "camera._lowBatAct"
#define ACCESS_CMD_TEST_MODULE_COMMUNICATION     "camera._test_module_communication"
#define ACCESS_CMD_TEST_MODULE_SPI               "camera._test_module_spi"
#define ACCESS_CMD_GET_MODULE_LOG_FILE           "camera._getModuleLogFile"
#define ACCESS_CMD_START_CAPTURE_AUDIO           "camera._startCaptureAudio"
#define ACCESS_CMD_STOP_CAPTURE_AUDIO            "camera._stopCaptureAudio"
#define ACCESS_CMD_SYSTEM_TIME_CHANGE            "camera._systemTimeChange"
#define ACCESS_CMD_STORAGE_TEST                  "camera._storage_test"
#define ACCESS_CMD_UPDATE_GAMMA_CURVE            "camera._update_gamma_curve"
#define ACCESS_CMD_CHANGE_MODULE_USB_MODE        "camera._change_module_usb_mode"
#define ACCESS_CMD_QUERY_GPS_STATUS              "camera._queryGpsStatus"
#define ACCESS_CMD_SET_GYRO_CAL_RES              "camera._setGyroCalibrationResult"
#define ACCESS_CMD_GET_GYRO_CAL_RES              "camera._getGyroCalibrationResult"
#define ACCESS_CMD_QUERY_BATTERY_TEMP            "camera._queryBatteryTemp"
#define ACCESS_CMD_DELETE_FILE                   "camera._deleteFile"
#define ACCESS_CMD_MODULE_POWON                  "camera._modulePowerOn"
#define ACCESS_CMD_MODULE_POWOFF                 "camera._modulePowerOff"
#define ACCESS_CMD_START_MAGMETER_CALIBRATION    "camera._startMagmeterCalibration"
#define ACCESS_CMD_STOP_MAGMETER_CALIBRATION     "camera._stopMagmeterCalibration"
#define ACCESS_CMD_CHANGE_UDISK_MODE             "camera._change_udisk_mode"

//to client cmd: end width "_"
#define ACCESS_CMD_RESET_INDICATION              "camera._resetIndication" //using in father process

#define ACCESS_CMD_RECORD_FINISH_                "camera._record_finish_"
#define ACCESS_CMD_PREVIEW_FINISH_               "camera._preview_finish_"
#define ACCESS_CMD_PIC_FINISH_                   "camera._pic_finish_"
#define ACCESS_CMD_LIVE_FINISH_                  "camera._live_finish_"
#define ACCESS_CMD_PIC_ORIGIN_FINISH_            "camera._pic_origin_finish_" 
#define ACCESS_CMD_LIVE_REC_FINISH_              "camera._live_rec_finish_" 
#define ACCESS_CMD_QR_SCAN_FINISH_               "camera._qr_scan_finish_"
#define ACCESS_CMD_CALIBRATION_FINISH_           "camera._calibration_finish_"
#define ACCESS_CMD_CALIBRATION_ORIGIN_FINISH_    "camera._calibration_origin_finish_"
#define ACCESS_CMD_NET_LINK_STATE_               "camera._net_link_state_" 
#define ACCESS_CMD_GYRO_CAL_FINISH_              "camera._gyro_calibration_finish_" 
#define ACCESS_CMD_MAGMETER_CAL_FINISH_          "camera._magmeter_calibration_finish_" 
#define ACCESS_CMD_STORAGE_ST_FINISH_            "camera._storage_speed_test_finish_" 
#define ACCESS_CMD_TIMELAPSE_PIC_TAKE_           "camera._timelapse_pic_take_" 
#define ACCESS_CMD_CAPTURE_AUDIO_FINISH_         "camera._capture_audio_finish_"
#define ACCESS_CMD_GPS_STATE_                    "camera._gps_state_"
#define ACCESS_CMD_SND_STATE_                    "camera._snd_state_"
#define ACCESS_CMD_BLC_RESULT                    "camera._calibrationBlcResult_"
#define ACCESS_CMD_BPC_RESULT                    "camera._calibrationBpcResult_"
#define ACCESS_CMD_STORAGE_STATE_                "camera._storage_state_"
#define ACCESS_CMD_DEL_FILE_FINISH_              "camera._delete_file_finish_"

//internal cmd: prefix = "internal"
#define INTERNAL_CMD_FIFO_CLOSE                    "internal.fifoClose"
#define INTERNAL_CMD_EXCEPTION                     "internal.exception"
#define INTERNAL_CMD_PIC_FINISH                    "internal.pic_finish"
#define INTERNAL_CMD_SINK_FINISH                   "internal.sink_finish"
#define INTERNAL_CMD_QR_SCAN_FINISH                "internal.qr_scan_finish"
#define INTERNAL_CMD_STORAGE_ST_F                  "internal.storage_speed_test_finish"
#define INTERNAL_CMD_PIC_ORIGIN_F                  "internal.pic_origin_finish"
#define INTERNAL_CMD_STORAGE_ST_F                  "internal.storage_speed_test_finish"
#define INTERNAL_CMD_GYRO_CALIBRATION_F            "internal.gyro_calibration_finish"
#define INTERNAL_CMD_MAGMETER_CALIBRATION_F        "internal.magmeter_calibration_finish"
#define INTERNAL_CMD_CALIBRATION_F                 "internal.calibration_finish"
#define INTERNAL_CMD_CAPTURE_AUDIO_F               "internal.capture_audio_finish"
#define INTERNAL_CMD_STOP_REC_F                    "internal.stop_record_finish"
#define INTERNAL_CMD_STOP_LIVE_F                   "internal.stop_live_finish"
#define INTERNAL_CMD_RESET                         "internal.reset"
#define INTERNAL_CMD_BLC_CAL_F                     "internal.blc_cal_finish"
#define INTERNAL_CMD_BPC_CAL_F                     "internal.bpc_cal_finish"
#define INTERNAL_CMD_SND_DEV_CHANGE                "internal.snd_dev_change"
#define INTERNAL_CMD_FIRST_FRAME_TS                "internal.first_frame_ts"
#define INTERNAL_CMD_VIDEO_FRAGMENT                "internal.video_fragment"
#define INTERNAL_CMD_VIG_MIN_CHANGE                "internal.vig_min_change"
#define INTERNAL_CMD_DEL_FILE_F                    "internal.delete_file_finish"

//stitching box msg(from client): prefix = "stitcher"
#define ACCESS_CMD_S_START_BOX          "stitcher.start_stitching_box"
#define ACCESS_CMD_S_STOP_BOX           "stitcher.stop_stitching_box"
#define ACCESS_CMD_S_START_TASK_LIST     "stitcher.start_task_list"
#define ACCESS_CMD_S_START_TASK_LIST     "stitcher.start_task_list"
#define ACCESS_CMD_S_STOP_TASK_LIST      "stitcher.stop_task_list"
#define ACCESS_CMD_S_QUERY_TASK_LIST     "stitcher.query_task_list"
#define ACCESS_CMD_S_ADD_TASK            "stitcher.add_task"
#define ACCESS_CMD_S_DELETE_TASK         "stitcher.delete_task"
#define ACCESS_CMD_S_START_TASK          "stitcher.start_task"
#define ACCESS_CMD_S_STOP_TASK           "stitcher.stop_task"
#define ACCESS_CMD_S_UPDATE_TASK         "stitcher.update_task"
#define ACCESS_CMD_S_QUERY_TASK          "stitcher.query_task"

//stitching box msg(to client): prefix = "stitcher"
//#define INTERNAL_CMD_S_TASK_STATS_       "internal_s.task_stats_"
#define ACCESS_CMD_S_TASK_STATS_         "stitcher.task_stats_"

#define ACCESS_MSG_NAME    				 "name"
#define ACCESS_MSG_PARAM   				 "parameters"
#define ACCESS_MSG_OPTION  				 "options"

#define ACCESS_MSG_STATE                          "state"
#define ACCESS_MSG_STATE_DONE                     "done"
#define ACCESS_MSG_STATE_INPROGRESS               "inProgress" //"progress": {"completion": 0}
#define ACCESS_MSG_STATE_ERROR                    "error"  //"error": {"code": "serverError","message": "cannot get camera info."}
#define ACCESS_MSG_STATE_ERR_UNKNOWCMD            "unknownCommand"
#define ACCESS_MSG_STATE_ERR_DISABLECMD           "disabledCommand"
#define ACCESS_MSG_STATE_ERR_CAMINEXCLUSIVEUSE    "cameraInExclusiveUse"
#define ACCESS_MSG_STATE_ERR_MISSPARAM            "missingParameter"
#define ACCESS_MSG_STATE_ERR_INVALIDPARAMNAME     "invalidParameterName"
#define ACCESS_MSG_STATE_ERR_INVALIDPARAMVALUE    "invalidParameterValue"

//option
#define ACCESS_MSG_OPT_RECORD_FORMAT   "_recordFormat"
#define ACCESS_MSG_OPT_PICTURE_FORMAT  "_pictureFormat"
#define ACCESS_MSG_OPT_PREVIEW_FORMAT  "previewFormat"
#define ACCESS_MSG_OPT_LIVE_FORMAT     "_liveFormat"
#define ACCESS_MSG_OPT_AUDIO_FORMAT    "_audioFormat"

#define ACCESS_MSG_OPT_MIME "mime"
#define ACCESS_MSG_OPT_FORMAT_WIDTH "width"
#define ACCESS_MSG_OPT_FORMAT_HEIGHT "height"
#define ACCESS_MSG_OPT_FORMAT_FRAMERATE "framerate"
#define ACCESS_MSG_OPT_FORMAT_BITRATE "bitrate"

#define ACCESS_MSG_OPT_FORMAT_SAMPLERATE "samplerate"
#define ACCESS_MSG_OPT_FORMAT_CHANNEL_LAYOUT "channelLayout"
#define ACCESS_MSG_OPT_FORMAT_SAMPLE_FORMAT "sampleFormat"
#define ACCESS_MSG_OPT_SAMPLEFMT_S16 "s16"
#define ACCESS_MSG_OPT_SAMPLEFMT_S32 "s32"
#define ACCESS_MSG_OPT_SAMPLEFMT_S24 "s24"
#define ACCESS_MSG_OPT_SAMPLEFMT_S24_3 "s24_3"
#define ACCESS_MSG_OPT_CHLAYOUT_MONO "mono"
#define ACCESS_MSG_OPT_CHLAYOUT_STEREO "stereo"

#define ACCESS_MSG_OPT_MAP "map"
#define ACCESS_MSG_OPT_VRMODE "mode"
#define ACCESS_MSG_OPT_VRMODE_3D "3d"
#define ACCESS_MSG_OPT_VRMODE_3D_TOP_LEFT "3d_top_left"
#define ACCESS_MSG_OPT_VRMODE_3D_TOP_RIGHT "3d_top_right"
#define ACCESS_MSG_OPT_VRMODE_PANO "pano"
#define ACCESS_MSG_OPT_LENS_SET "lensSet"
#define ACCESS_MSG_OPT_ALGORITHM "algorithm"
#define ACCESS_MSG_OPT_OFFSET_PANO_4_3 "offset_pano_4_3"
#define ACCESS_MSG_OPT_OFFSET_PANO_16_9 "offset_pano_16_9"
#define ACCESS_MSG_OPT_OFFSET_3D_LEFT "offset_3d_left"
#define ACCESS_MSG_OPT_OFFSET_3D_RIGHT "offset_3d_right"

#define ACCESS_MSG_OPT_STICHING "stiching"
#define ACCESS_MSG_OPT_ORIGIN "origin"
#define ACCESS_MSG_OPT_AUDIO "audio"
#define ACCESS_MSG_OPT_BURST "burst"
#define ACCESS_MSG_OPT_HDR "hdr"
#define ACCESS_MSG_OPT_IMAGE_PROPERTY "imageProperty"
#define ACCESS_MSG_OPT_SAVE_ORIGIN "saveOrigin"
#define ACCESS_MSG_OPT_CAMERA_INDEX "cameraIndex"
#define ACCESS_MSG_OPT_LIVEONHDMI "liveOnHdmi"
#define ACCESS_MSG_OPT_PATH "path"
#define ACCESS_MSG_OPT_DATA "data"
#define ACCESS_MSG_OPT_INDEX "index"
#define ACCESS_MSG_OPT_DELAY "delay"
#define ACCESS_MSG_OPT_ORIGIN_OVER "originOver"
#define ACCESS_MSG_OPT_REC_OVER "recOver"
#define ACCESS_MSG_OPT_ALL_OVER "allOver"
#define ACCESS_MSG_OPT_STORAGE_LOC "storage_loc"

#define ACCESS_MSG_OPT_LIVE_URL "_liveUrl"
#define ACCESS_MSG_OPT_PREVIEW_URL "_previewUrl"
#define ACCESS_MSG_OPT_PIC_URL "_picUrl"
#define ACCESS_MSG_OPT_RECORD_URL "_recordUrl"
#define ACCESS_MSG_OPT_FILE_URL "_fileUrl"

#define ACCESS_MSG_OPT_MIME_H264 "h264"
#define ACCESS_MSG_OPT_MIME_H265 "h265"
#define ACCESS_MSG_OPT_MIME_JPEG "jpeg"
#define ACCESS_MSG_OPT_MIME_RAW "raw"
#define ACCESS_MSG_OPT_MIME_RAW_JPEG "raw+jpeg"
#define ACCESS_MSG_OPT_MIME_AAC  "aac"

#define ACCESS_MSG_OPT_PROPERTY "property"
#define ACCESS_MSG_OPT_VALUE "value"

#define ACCESS_MSG_OPT_STABILIZATION "stabilization"
#define ACCESS_MSG_OPT_MODULE_VERSION "moduleVersion"
#define ACCESS_MSG_OPT_VERSION "version"
#define ACCESS_MSG_OPT_STORAGE_PATH "storagePath"
#define ACCESS_MSG_OPT_AUDIO_GAIN "audio_gain"
#define ACCESS_MSG_OPT_DEPTH_MAP "depthMap"
#define ACCESS_MSG_OPT_IQTYPE "IQType"
#define ACCESS_MSG_OPT_GYRO_CAL_RES "gyro_cal_result"
#define ACCESS_MSG_OPT_BLC_STATE "blc_state"
#define ACCESS_MSG_OPT_STORAGE_CAP "storage_capacity"
#define ACCESS_MSG_OPT_STORAGE_TOTAL "storage_total"
#define ACCESS_MSG_OPT_STORAGE_LEFT "storage_left"

#define ACCESS_MSG_OPT_3A_MODE "aaa_mode"
#define ACCESS_MSG_OPT_3A_MODE_AUTO "auto"
#define ACCESS_MSG_OPT_3A_MODE_MANUAL "manual"
#define ACCESS_MSG_OPT_WB "wb"
#define ACCESS_MSG_OPT_ISO "iso"
#define ACCESS_MSG_OPT_SHUTTER "shutter"  
#define ACCESS_MSG_OPT_BRIGHTNESS "brightness" 
#define ACCESS_MSG_OPT_CONSTRAST "contrast" 
#define ACCESS_MSG_OPT_SATURATION "saturation" 
#define ACCESS_MSG_OPT_HUE "hue" 
#define ACCESS_MSG_OPT_SHARPNESS "sharpness" 
#define ACCESS_MSG_OPT_EV_BIAS "ev_bias" 
#define ACCESS_MSG_OPT_AE_METER "ae_meter" 
#define ACCESS_MSG_OPT_DIG_EFFECT "dig_effect" 
#define ACCESS_MSG_OPT_FLICKER "flicker" 
#define ACCESS_MSG_OPT_IMGPARAM "imgParam" 
#define ACCESS_MSG_OPT_FANLESS "fanless" 
#define ACCESS_MSG_OPT_PANO_AUDIO "panoAudio"
#define ACCESS_MSG_OPT_AUDIO_TO_STITCH "audiotoStitch"
#define ACCESS_MSG_OPT_SUPPORT_FUNCTION "supportedFunctions"
#define ACCESS_MSG_OPT_STABLIZATION_CFG "stabilization_cfg"
#define ACCESS_MSG_OPT_STABLIZATION_TYPE "stabilization_type"
#define ACCESS_MSG_OPT_LOGO 				"logo"
#define ACCESS_MSG_OPT_VIDEO_FRAGMENT 		"video_fragment"

#define ACCESS_MSG_OPT_BITDEPTH 			"bitDepth"
#define ACCESS_MSG_OPT_LOGMODE 				"logMode"
#define ACCESS_MSG_OPT_HDR 					"hdr"
#define ACCESS_MSG_OPT_BRACKET 				"bracket"
#define ACCESS_MSG_OPT_LOGMODE_EFFECT 		"effect"
#define ACCESS_MSG_OPT_LOGMODE_MODE 		"mode"

#define ACCESS_MSG_OPT_FILE_SIZE_KB 		"fileSizeKB"

#endif
